[package]
name = "mail-core"
version.workspace = true
edition.workspace = true
license.workspace = true
[lib]
crate-type = ["lib", "staticlib", "cdylib"]
[dependencies]
mail-model.workspace = true
mail-db.workspace = true
mail-sync.workspace = true
thiserror.workspace = true
uniffi = { workspace = true, features = ["cli"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
clap = { version = "4", features = ["derive"] }
serde_json = "1"
rpassword = "7"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
