[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
mail-model = { path = "crates/mail-model", version = "0.1.0" }
mail-autoconfig = { path = "crates/mail-autoconfig", version = "0.1.0" }
mail-db = { path = "crates/mail-db", version = "0.1.0" }
mail-imap = { path = "crates/mail-imap", version = "0.1.0" }
mail-mime = { path = "crates/mail-mime", version = "0.1.0" }
mail-sync = { path = "crates/mail-sync", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
uniffi = "0.32"

[workspace.lints.rust]
unsafe_code = "forbid"
unused_must_use = "deny"
rust_2018_idioms = { level = "warn", priority = -1 }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
