name: Required quality checks
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  rust-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetify-com/devbox-install-action@a0d2d53632934ae004f878c840055956d9f741b0 # v0.14.0
      - run: devbox run check-rust
  apple-quality:
    runs-on: macos-15-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: jetify-com/devbox-install-action@a0d2d53632934ae004f878c840055956d9f741b0 # v0.14.0
      - run: devbox run check-swift
